# Generated by Django 2.0.3 on 2018-03-07 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('contact_mobile', models.CharField(blank=True, max_length=10, verbose_name='contact mobile')),
                ('has_breed', models.BooleanField(default=True, verbose_name='has breed')),
                ('has_herd', models.BooleanField(default=True, verbose_name='has herd')),
                ('has_weight', models.BooleanField(default=True, verbose_name='has weight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
