# Generated by Django 2.0 on 2017-12-30 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_lactating',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='animal',
            name='milk_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='milk_evening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='milk_morning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gears.Animal'),
        ),
    ]
