# Generated by Django 2.0.3 on 2018-03-07 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gears', '0001_initial'),
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='default_identity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.IdentityType', verbose_name='default identity type'),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
