# Generated by Django 2.0.3 on 2018-03-08 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0002_auto_20180308_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name': 'farm', 'verbose_name_plural': 'farms'},
        ),
        migrations.AlterField(
            model_name='farm',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
