# Generated by Django 2.0 on 2017-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0002_auto_20171230_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltxn',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animaltxn',
            name='amount',
            field=models.FloatField(),
        ),
    ]
