# Generated by Django 2.0 on 2018-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0004_auto_20180301_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalsickness',
            name='description',
            field=models.CharField(default='asdfasdf', max_length=200),
            preserve_default=False,
        ),
    ]
