# Generated by Django 2.0 on 2018-03-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0005_animalsickness_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='milk_evening',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='milk_morning',
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gears.Breed', verbose_name='breed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth (AD)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dob_bs',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='date of birth (BS)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_lactating',
            field=models.BooleanField(default=False, verbose_name='is lactating'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_sick',
            field=models.BooleanField(default=False, verbose_name='is sick'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='milk_day',
            field=models.FloatField(blank=True, null=True, verbose_name='milk per day'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='tag'),
        ),
    ]
