# Generated by Django 2.0 on 2018-03-02 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gears', '0006_auto_20180301_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('name_np', models.CharField(max_length=50, verbose_name='name np')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SicknessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_np', models.CharField(max_length=100, verbose_name='name np')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='is_lactating',
        ),
        migrations.AddField(
            model_name='animal',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_pregnant',
            field=models.BooleanField(default=False, verbose_name='is pregnant'),
        ),
        migrations.AddField(
            model_name='animal',
            name='lactation',
            field=models.CharField(choices=[('Never lactated', 'Never lactated'), ('Lactating', 'Lactating'), ('Stopped', 'Stopped')], default='Never lactated', max_length=20, verbose_name='lactation'),
        ),
        migrations.AddField(
            model_name='animalsickness',
            name='is_recovered',
            field=models.BooleanField(default=False, verbose_name='is recovered'),
        ),
        migrations.AddField(
            model_name='animalsickness',
            name='recovered_on',
            field=models.DateField(blank=True, null=True, verbose_name='recovered on'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='milk_day',
            field=models.FloatField(blank=True, null=True, verbose_name='milk per day (in litres)'),
        ),
        migrations.AlterField(
            model_name='animalsickness',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='animalevent',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gears.Animal'),
        ),
        migrations.AddField(
            model_name='animalevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalevent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gears.AnimalEventType'),
        ),
    ]
