# Generated by Django 2.0.3 on 2018-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0006_auto_20180310_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='has_breed',
            field=models.BooleanField(default=True, help_text='If enabled, will show breed field while adding/updating animals.', verbose_name='show breed field'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='has_herd',
            field=models.BooleanField(default=True, help_text='If enabled, will show herd field while adding/updating animals.', verbose_name='show herd field'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='has_weight',
            field=models.BooleanField(default=True, help_text='If enabled, will show weight field while adding/updating animals.', verbose_name='show weight field'),
        ),
    ]
