# Generated by Django 2.0.3 on 2018-03-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
    ]
