# Generated by Django 2.0.3 on 2018-03-08 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0003_auto_20180308_0752'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'animal medication',
                'verbose_name_plural': 'animal medications',
            },
        ),
        migrations.CreateModel(
            name='MedicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
            ],
            options={
                'verbose_name': 'medication type',
                'verbose_name_plural': 'medication types',
            },
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='txn',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'animal', 'verbose_name_plural': 'animals'},
        ),
        migrations.AlterModelOptions(
            name='animalevent',
            options={'verbose_name': 'animal event', 'verbose_name_plural': 'animal events'},
        ),
        migrations.AlterModelOptions(
            name='animaleventtype',
            options={'verbose_name': 'animal event type', 'verbose_name_plural': 'animal sickness types'},
        ),
        migrations.AlterModelOptions(
            name='animalsickness',
            options={'verbose_name': 'animal sickness', 'verbose_name_plural': 'animal sickness'},
        ),
        migrations.AlterModelOptions(
            name='animaltxn',
            options={'verbose_name': 'animal transaction', 'verbose_name_plural': 'animal transactions'},
        ),
        migrations.AlterModelOptions(
            name='sicknesstype',
            options={'verbose_name': 'sickness type', 'verbose_name_plural': 'sicknes types'},
        ),
        migrations.AlterModelOptions(
            name='txntype',
            options={'verbose_name': 'transaction type', 'verbose_name_plural': 'transaction types'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='name',
        ),
        migrations.AddField(
            model_name='animaltxn',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gears.Farm', verbose_name='farm'),
        ),
        migrations.AddField(
            model_name='identitytype',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='animalevent',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='livestock.Animal', verbose_name='animal'),
        ),
        migrations.AlterField(
            model_name='animalevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='animalevent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='livestock.AnimalEventType', verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='animalevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='animaleventtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='animalsickness',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Animal', verbose_name='animal'),
        ),
        migrations.AlterField(
            model_name='animalsickness',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='animaltxn',
            name='amount',
            field=models.FloatField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='animaltxn',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.Animal', verbose_name='animal'),
        ),
        migrations.AlterField(
            model_name='animaltxn',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='animaltxn',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livestock.TxnType', verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='animaltxn',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='breed',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='herd',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='identitytype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='sicknesstype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='txntype',
            name='is_expense',
            field=models.BooleanField(default=False, verbose_name='is expense'),
        ),
        migrations.AlterField(
            model_name='txntype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='txntype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='MedicineType',
        ),
        migrations.AddField(
            model_name='animalmedication',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Animal', verbose_name='animal'),
        ),
        migrations.AddField(
            model_name='animalmedication',
            name='txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.AnimalTxn', verbose_name='transaction'),
        ),
        migrations.AddField(
            model_name='animalmedication',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.MedicationType', verbose_name='medication type'),
        ),
    ]
