# Generated by Django 2.0.3 on 2018-03-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20180308_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitytype',
            name='short_name',
        ),
    ]
