# Generated by Django 2.0.3 on 2018-03-10 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_auto_20180308_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltxn',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gears.Farm', verbose_name='farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='herd',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
