# Generated by Django 2.0.3 on 2018-03-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_auto_20180310_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='animalevent',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='animaleventtype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='animalmedication',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='animalsickness',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='animaltxn',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='herd',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='identitytype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='medicationtype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='sicknesstype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='txntype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Set this to True to soft-delete', verbose_name='is deleted'),
        ),
    ]
