# Generated by Django 2.0.3 on 2018-03-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0009_auto_20180310_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='net_expense',
            field=models.FloatField(default=0, verbose_name='net expense'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='net_income',
            field=models.FloatField(default=0, verbose_name='net income'),
        ),
    ]
