# Generated by Django 2.0.3 on 2018-03-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0010_auto_20180311_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalsickness',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livestock.SicknessType', verbose_name='sickness type'),
            preserve_default=False,
        ),
    ]
