# Generated by Django 2.0.3 on 2018-03-12 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0011_animalsickness_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmedication',
            name='sickness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.AnimalSickness', verbose_name='sickness'),
        ),
    ]
