# Generated by Django 2.0.3 on 2018-03-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0007_auto_20180311_2240'),
        ('livestock', '0012_animalmedication_sickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='herd',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gears.Farm', verbose_name='farm'),
            preserve_default=False,
        ),
    ]
